#!/usr/bin/env node
// Shared-checkout coordination. No network, credentials, database or deployment access.
import { readFileSync, writeFileSync, mkdirSync, renameSync, rmSync, existsSync, readdirSync } from "node:fs";
import { resolve, dirname, relative, join } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { randomUUID, createHash } from "node:crypto";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STATE = join(ROOT, "docs/project-state.json");
const LOCK = join(ROOT, ".compass-coordination.lock");
const ACTORS = ["codex", "minimax", "polar"];
const STATUS = ["backlog", "ready", "in_progress", "in_review", "changes_requested", "done", "blocked"];
const [command = "status", ...args] = process.argv.slice(2);
const git = (...argv) => execFileSync("git", argv, { cwd: ROOT, encoding: "utf8" }).trim();
const read = (path) => JSON.parse(readFileSync(path, "utf8"));
const state = () => read(STATE);
function atomic(path, value) {
  const tmp = `${path}.${randomUUID()}.tmp`;
  writeFileSync(tmp, value, "utf8");
  renameSync(tmp, path);
}
function fail(message) { throw new Error(message); }
function actor(name) { if (!ACTORS.includes(name)) fail(`Actor must be ${ACTORS.join(", ")}.`); return name; }
function task(s, id) { const t = s.tasks.find((item) => item.id === id); if (!t) fail(`Unknown task ${id}.`); return t; }
function branch(s) {
  if (ROOT.toLowerCase().includes("onedrive")) fail("Retired OneDrive checkout. Work only in C:\\dev\\compass.");
  const current = git("branch", "--show-current");
  // Actions checks a synthetic detached PR merge; it is read-only validation.
  if (command === "check" && process.env.GITHUB_ACTIONS === "true" && !current && process.env.GITHUB_BASE_REF === s.repository.branch) return;
  if (current !== s.repository.branch) fail(`Expected branch ${s.repository.branch}; stop and reconcile.`);
}
function claimRecord() { if (!existsSync(join(LOCK, "claim.json"))) fail("No complete writer claim. Run claim, or inspect a partial lock before recovery."); return read(join(LOCK, "claim.json")); }
function requireClaim(who, id) {
  const claim = claimRecord();
  if (claim.actor !== who || claim.task !== id) fail(`Checkout is owned by ${claim.actor} for ${claim.task}.`);
  return claim;
}
function save(s) { s.updatedOn = new Date().toISOString().slice(0, 10); atomic(STATE, `${JSON.stringify(s, null, 2)}\n`); generate(s); }
function fingerprint() {
  // The index defines membership; bytes come from disk to detect unstaged edits.
  // Ignored scratch files cannot change the digest between local and clean CI.
  const evidence = new Set(["docs/project-state.json", "COORDINATION.md"]);
  const teamContracts = new Set(["PROTOCOL.md", "MINIMAX.md", "POLAR.md", "HANDOFF-TEMPLATE.md", "START-POLAR.txt", "START-MINIMAX.txt"]);
  const paths = git("ls-files", "--cached", "-z").split("\0").filter((path) =>
    path && governed(path) && !evidence.has(path) &&
    (!path.startsWith("docs/team/") || teamContracts.has(path.slice("docs/team/".length))) && existsSync(join(ROOT, path)));
  const hash = createHash("sha256");
  for (const path of paths.sort()) {
    const bytes = readFileSync(join(ROOT, path));
    // Normalize text line endings so Windows and Linux yield the same digest.
    const data = /\.(ts|tsx|js|mjs|json|yaml|yml|md|css|sql|prisma|html|svg|toml|sh|cmd|bat|ps1|txt|conf)$/.test(path) || ([".gitignore", ".gitattributes", ".editorconfig"].includes(path) || path.endsWith(".example") || path.startsWith(".githooks/")) ? bytes.toString("utf8").replaceAll("\r\n", "\n") : bytes;
    hash.update(path); hash.update("\0"); hash.update(data); hash.update("\0");
  }
  return hash.digest("hex");
}
function generate(s) {
  s.repository.contentDigest = fingerprint();
  atomic(STATE, `${JSON.stringify(s, null, 2)}\n`);
  atomic(join(ROOT, "COORDINATION.md"), render(s));
}
function render(s) {
  const lines = ["# Compass — current coordination", "", "> GENERATED from docs/project-state.json by node scripts/project-sync.mjs generate. Do not edit this file directly.", "", `Updated: ${s.updatedOn}. Repository baseline: \`${s.repository.baselineCommit}\` (recorded audit baseline, not a deployment verdict).`, "", "Read [AGENTS.md](AGENTS.md), [team protocol](docs/team/PROTOCOL.md), [product vision](00-VISION.md), and [design contract](00-DESIGN.md).", "", "## Current focus", "", `Active task: **${s.activeTask ?? "none"}**. Functional backlog stays queued until alignment review is complete.`, "", "## Team", "", "| App | Default role | Status |", "| --- | --- | --- |"];
  for (const [name, entry] of Object.entries(s.team)) lines.push(`| ${name} | ${entry.role} | ${entry.status} |`);
  lines.push("", "## Shared task queue", "", "| ID | Task | Status | Owner | Reviewer |", "| --- | --- | --- | --- | --- |");
  for (const t of s.tasks) lines.push(`| ${t.id} | ${t.title} | ${t.status} | ${t.owner ?? "unassigned"} | ${t.reviewer ?? "unassigned"} |`);
  lines.push("", "## Implementation facts", "", "Postgres-everywhere: prisma/schema.prisma and src/server/db.ts use PostgreSQL / PrismaPg. Exact package versions are in package.json and pnpm-lock.yaml.", "");
  for (const [key, value] of Object.entries(s.implementation)) lines.push(`- **${key}**: ${value}`);
  lines.push("", "## Verification evidence", "");
  for (const v of s.verification) lines.push(`- **${v.check}** — ${v.result}. Evidence: ${v.evidence}. ${v.note ?? ""}`);
  lines.push("", "## Deployment status", "", `${s.deployments.status}. ${s.deployments.note} Reference: [historical snapshot](${s.deployments.reference}).`, "", "## Decision revisions", "");
  for (const d of s.decisions) lines.push(`- **${d.id} (${d.date})**: ${d.text}`);
  lines.push("", "## Handoffs and reviews", "");
  for (const t of s.tasks.filter((item) => item.handoff || item.review)) {
    if (t.handoff) lines.push(`- ${t.id} handoff: [${t.handoff.path}](${t.handoff.path}); based on \`${t.handoff.head}\`.`);
    if (t.review) lines.push(`- ${t.id} review: **${t.review.verdict}** by ${t.review.actor}${t.review.mode === "remote-proxy" ? ` (remote; recorded by ${t.review.recordedBy})` : ""}; [report](${t.review.path}); based on \`${t.review.head}\`; report SHA-256 \`${t.review.sha256 ?? "legacy record"}\`.`);
  }
  lines.push("", "History: [archive](docs/archive/2026-10-08/README.md). Historical prompts, old NEXT labels, and old CI results never assign current work.", "");
  return lines.join("\n");
}
function validate(s) {
  if (s.schemaVersion !== 1 || s.project !== "Compass") fail("Unsupported project state.");
  const ids = new Set();
  for (const t of s.tasks) {
    if (ids.has(t.id)) fail(`Duplicate task ${t.id}.`); ids.add(t.id);
    if (!STATUS.includes(t.status)) fail(`Invalid status for ${t.id}.`);
    for (const who of [t.owner, t.reviewer].filter(Boolean)) actor(who);
    if (t.owner && t.owner === t.reviewer) fail(`${t.id} needs an independent reviewer.`);
    if (t.status !== "backlog" && (!t.owner || !t.reviewer || !Array.isArray(t.scope) || !t.scope.length || !Array.isArray(t.acceptance) || !t.acceptance.length)) fail(`${t.id} lacks assignment, scope or acceptance.`);
    if (["in_review", "done"].includes(t.status) && !t.handoff) fail(`${t.id} lacks a handoff.`);
    if (t.status === "done" && t.review?.verdict !== "approved") fail(`${t.id} lacks an approved review.`);
    for (const evidence of [t.handoff, t.review].filter(Boolean)) {
      if (!existsSync(join(ROOT, evidence.path))) fail(`${t.id} missing evidence ${evidence.path}.`);
      if (evidence.sha256 && createHash("sha256").update(readFileSync(join(ROOT, evidence.path))).digest("hex") !== evidence.sha256) fail(`${t.id} evidence hash changed: ${evidence.path}.`);
    }
  }
  if (s.activeTask && !ids.has(s.activeTask)) fail("Active task is missing.");
  const active = s.tasks.filter((t) => ["ready", "in_progress", "in_review", "changes_requested"].includes(t.status));
  if (active.length > 1 || (active.length === 1 && s.activeTask !== active[0].id)) fail("Only one active task is allowed, and activeTask must match.");
  if (readFileSync(join(ROOT, "COORDINATION.md"), "utf8") !== render(s)) fail("COORDINATION.md drifted. Run project:sync.");
  if (s.repository.contentDigest !== fingerprint()) fail("Maintained code/docs changed without a shared-state refresh. Update evidence and run project:sync while holding the claim.");
  for (const f of ["AGENTS.md", "README.md", "HANDOVER.md", "HANDOVER-TEST-INTEGRITY.md", "CLAUDE.md", "docs/team/MINIMAX.md", "docs/team/POLAR.md"]) {
    if (!readFileSync(join(ROOT, f), "utf8").includes("COORDINATION.md")) fail(`${f} must point to shared coordination.`);
  }
  for (const f of ["AGENTS.md", "README.md", "HANDOVER.md", "HANDOVER-TEST-INTEGRITY.md", "CLAUDE.md", ...readdirSync(join(ROOT, "docs/team")).filter((p) => p.endsWith(".md")).map((p) => `docs/team/${p}`)]) {
    for (const match of readFileSync(join(ROOT, f), "utf8").matchAll(/\]\(([^)\s]+\.md)(?:#[^)]*)?\)/g)) {
      if (/^[a-z]+:/i.test(match[1])) continue;
      if (!existsSync(resolve(dirname(join(ROOT, f)), match[1]))) fail(`${f} has broken link ${match[1]}.`);
    }
  }
  if (!/provider\s*=\s*"postgresql"/.test(readFileSync(join(ROOT, "prisma/schema.prisma"), "utf8"))) fail("Database contract drift: PostgreSQL expected.");
  if (!readFileSync(join(ROOT, "src/server/db.ts"), "utf8").includes("PrismaPg")) fail("Database adapter drift.");
  for (const f of readdirSync(ROOT)) if (/^00-(CLUSTER|POLAR)-.*\.md$/.test(f)) fail(`Historical spec returned to root: ${f}. Archive it and assign current work in project-state.json.`);
  branch(s);
}
function reportPath(value, expected) {
  if (!value) fail("Provide an evidence path under docs/team/.");
  const full = resolve(ROOT, value); const rel = relative(ROOT, full).replaceAll("\\", "/");
  if (!rel.startsWith("docs/team/") || !existsSync(full)) fail("Evidence must be an existing file under docs/team/.");
  const body = readFileSync(full, "utf8");
  for (const marker of ["Task:", "Author:", "Base commit:", "Changed files:", "Validation:", "Risks:", "Next owner:"]) if (!body.includes(marker)) fail(`Evidence missing ${marker}`);
  if (expected) {
    const field = (name) => body.match(new RegExp(`^${name}:\\s*(.+)$`, "m"))?.[1].trim();
    if (field("Task") !== expected.id || field("Author") !== expected.actor || field("Base commit") !== git("rev-parse", "HEAD")) fail("Report task, author and exact base commit must match the command and HEAD.");
    if (expected.verdict && field("Verdict") !== expected.verdict) fail("Report Verdict must match the command.");
    if (expected.handoff && rel === expected.handoff) fail("Review report must differ from the implementation handoff.");
  }
  return rel;
}
function proxyOptions(who, extra) {
  if (!extra.length) {
    if (state().team[who]?.accessMode === "remote") fail("Remote reviewer requires explicit proxy recording options; do not claim local execution.");
    return { mode: "local", recordedBy: who };
  }
  if (extra.length !== 4 || extra[0] !== "--recorded-by" || extra[1] !== "codex" || extra[2] !== "--report-sha256" || !/^[a-f0-9]{64}$/.test(extra[3]) || who !== "polar") fail("Remote proxy requires polar, --recorded-by codex --report-sha256 <reviewer-confirmed SHA-256>.");
  return { mode: "remote-proxy", recordedBy: "codex", sha256: extra[3] };
}
function acquireClaim(record, mutate) {
  if (existsSync(LOCK)) fail(`Writer claim already exists: ${existsSync(join(LOCK, "claim.json")) ? JSON.stringify(claimRecord()) : "partial lock; recover explicitly"}.`);
  mkdirSync(LOCK);
  try { atomic(join(LOCK, "claim.json"), `${JSON.stringify(record, null, 2)}\n`); mutate?.(); }
  catch (error) { rmSync(LOCK, { recursive: true, force: true }); throw error; }
}
function governed(path) {
  if (path.startsWith("src/generated/")) return false;
  return /^(src|prisma|scripts|tests|public|docker|compass-landing|\.github|\.githooks|docs\/team)\//.test(path) || ["docs/project-state.json", "COORDINATION.md", "AGENTS.md", "CLAUDE.md", "README.md", "00-DESIGN.md", "00-VISION.md", "00-MOM-LAUNCH-RUNBOOK.md", "VERCEL-DEPLOYMENTS.md", "HANDOVER.md", "HANDOVER-TEST-INTEGRITY.md", "package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "next.config.ts", "prisma.config.ts", "tsconfig.json", "eslint.config.mjs", "postcss.config.mjs", "vercel.json", "instrumentation.ts", "docker-compose.dev.yml", "components.json", ".env.example", ".env.local.example", ".env.production.example", ".gitignore", ".gitattributes", ".editorconfig", "docs/compass-vision.md", "docs/compass-vision-summary.md", "docs/COMPASS-AS-A-BUSINESS.md", "design/README.md", "DeFi/README.md", "DeFi/Compass vault spec.md"].includes(path);
}
function envUrl(path) {
  if (!existsSync(path)) return null;
  const match = readFileSync(path, "utf8").match(/^\s*(?:export\s+)?DATABASE_URL\s*=\s*(.*)$/m);
  if (!match) return null;
  const value = match[1].trim();
  if (value.startsWith('"') || value.startsWith("'")) {
    const end = value.lastIndexOf(value[0]); return end > 0 ? value.slice(1, end) : null;
  }
  return value.replace(/\s+#.*$/, "").trim();
}
try {
  const s = state();
  if (command === "status") {
    branch(s);
    console.log(JSON.stringify({ branch: s.repository.branch, head: git("rev-parse", "--short", "HEAD"), activeTask: s.activeTask, lock: existsSync(LOCK) ? (existsSync(join(LOCK, "claim.json")) ? claimRecord() : "partial lock — recover explicitly") : null, team: s.team }, null, 2));
  } else if (command === "check") {
    validate(s); console.log("project alignment: clean");
  } else if (command === "check-index") {
    validate(s);
    const unstaged = git("diff", "--name-only", "-z").split("\0").filter((path) => path && governed(path));
    const untracked = git("ls-files", "--others", "--exclude-standard", "-z").split("\0").filter((path) => path && governed(path));
    if (unstaged.length || untracked.length) fail(`Maintained files are unstaged/untracked: ${[...unstaged, ...untracked].join(", ")}. Review and stage explicit task paths with matching state; do not commit a partial snapshot.`);
    console.log("staged project snapshot matches maintained working files");
  } else if (command === "env-check") {
    branch(s);
    if (process.env.DATABASE_URL) console.log("DATABASE_URL is explicitly supplied to this shell. No secret value displayed and no environment file changed.");
    else {
      const cli = envUrl(join(ROOT, ".env")); const runtime = envUrl(join(ROOT, ".env.local")) ?? cli;
      if (!cli || !runtime) fail("Local DATABASE_URL is missing. Choose the intended local database before migrations/tests; no environment file or database was changed.");
      if (cli !== runtime) fail("DATABASE_URL differs between CLI .env and runtime .env.local. Supply an explicit intended local target before migrations/tests; no secret value displayed and no configuration/database changed.");
      console.log("CLI/runtime DATABASE_URL file values match. This checks configuration only, not connectivity or migration state.");
    }
  } else if (command === "install-hooks") {
    const claim = claimRecord(); requireClaim(claim.actor, s.activeTask); branch(s);
    let existing = "";
    try { existing = git("config", "--get", "core.hooksPath"); } catch (error) { if (error.status !== 1) throw error; }
    if (existing && existing !== ".githooks") fail(`Existing hooksPath ${existing}; preserve it and integrate the Compass guard there explicitly.`);
    git("config", "--local", "core.hooksPath", ".githooks"); console.log("Local pre-commit alignment guard installed.");
  } else if (command === "generate") {
    // Updating the generated document is allowed only by the active writer.
    const claim = claimRecord(); requireClaim(claim.actor, s.activeTask); branch(s); generate(s); console.log("COORDINATION.md generated");
  } else if (command === "claim") {
    const [who, id, ...extra] = args; actor(who); branch(s); const t = task(s, id); const mode = proxyOptions(who, extra);
    if (s.activeTask !== id || !["ready", "in_progress", "in_review", "changes_requested"].includes(t.status)) fail("Task is not the single authorized active task.");
    const expected = t.status === "in_review" ? t.reviewer : t.owner;
    if (who !== expected) fail(`Task expects ${expected} at this stage.`);
    if (mode.mode === "remote-proxy" && t.status !== "in_review") fail("Proxy claims are for review recording only.");
    acquireClaim({ actor: who, task: id, ...mode, claimedAt: new Date().toISOString(), head: git("rev-parse", "HEAD") }, () => { if (t.status === "ready") { t.status = "in_progress"; save(s); } });
    console.log(`Claimed ${id} for ${who}. Read task scope before editing.`);
  } else if (command === "release") {
    const [who, id] = args; actor(who); requireClaim(who, id); branch(s); rmSync(LOCK, { recursive: true }); console.log("Writer claim released; task status unchanged.");
  } else if (command === "ack") {
    const [who, ...extra] = args; actor(who); const claim = claimRecord(); requireClaim(who, s.activeTask); branch(s); const mode = proxyOptions(who, extra);
    if (mode.mode !== (claim.mode ?? "local") || mode.sha256 !== claim.sha256) fail("Acknowledgement must match claim recording mode and report hash.");
    s.team[who].status = mode.mode === "remote-proxy" ? "remote reviewer; protocol read acknowledgement supplied remotely; no local acknowledgement" : "protocol acknowledged";
    s.team[who].acknowledgement = { ...mode, at: new Date().toISOString() }; save(s); console.log(`${who} acknowledgement recorded by ${mode.recordedBy} (${claim.task}, ${mode.mode}).`);
  } else if (command === "handoff") {
    const [who, id, path] = args; actor(who); requireClaim(who, id); branch(s); const t = task(s, id);
    if (t.owner !== who || !["in_progress", "changes_requested"].includes(t.status)) fail("Only the task owner may hand off implementation.");
    const report = reportPath(path, { id, actor: who });
    const sha256 = createHash("sha256").update(readFileSync(join(ROOT, report))).digest("hex");
    t.handoff = { path: report, sha256, actor: who, head: git("rev-parse", "HEAD"), contentDigest: fingerprint(), at: new Date().toISOString() }; t.review = null; t.status = "in_review";
    save(s); rmSync(LOCK, { recursive: true }); console.log(`Handed ${id} to ${t.reviewer}. Review must cover the working diff as well as HEAD.`);
  } else if (command === "review") {
    const [who, id, verdict, path, ...extra] = args; actor(who); const claim = requireClaim(who, id); branch(s); const t = task(s, id); const mode = proxyOptions(who, extra);
    if (t.reviewer !== who || t.status !== "in_review") fail("Only the assigned reviewer may review this handoff.");
    if (!["approved", "changes_requested"].includes(verdict)) fail("Verdict must be approved or changes_requested.");
    if (t.handoff.sha256 && createHash("sha256").update(readFileSync(join(ROOT, t.handoff.path))).digest("hex") !== t.handoff.sha256) fail("Implementation handoff bytes changed; require a fresh owner handoff before review.");
    if (verdict === "approved" && t.handoff.contentDigest !== fingerprint()) fail("Implementation changed since handoff. Request changes and require a fresh handoff before approval.");
    const report = reportPath(path, { id, actor: who, verdict, handoff: t.handoff.path });
    const sha256 = createHash("sha256").update(readFileSync(join(ROOT, report))).digest("hex");
    if (mode.mode !== (claim.mode ?? "local") || (mode.mode === "remote-proxy" && (sha256 !== mode.sha256 || sha256 !== claim.sha256))) fail("Remote report bytes and reviewer-confirmed hash must match the proxy claim and verdict.");
    t.review = { path: report, actor: who, verdict, ...mode, sha256, head: git("rev-parse", "HEAD"), contentDigest: fingerprint(), at: new Date().toISOString() };
    t.status = verdict === "approved" ? "done" : "changes_requested";
    if (t.status === "done") s.activeTask = null;
    save(s); rmSync(LOCK, { recursive: true }); console.log(`${id}: ${verdict}. Review completion is not a commit, push or deployment.`);
  } else if (command === "assign") {
    const [who, id, owner, reviewer, scopeCsv, acceptanceText] = args; actor(who); actor(owner); actor(reviewer); branch(s);
    if (who !== "codex" || s.activeTask || existsSync(LOCK)) fail("Codex assigns the next task only after the previous task and writer claim are closed.");
    const t = task(s, id); if (t.status !== "backlog") fail("Only backlog tasks can be assigned.");
    const scope = scopeCsv ? scopeCsv.split(",").map((value) => value.trim()).filter(Boolean) : t.scope;
    const acceptance = acceptanceText ? acceptanceText.split("|").map((value) => value.trim()).filter(Boolean) : t.acceptance;
    if (owner === reviewer || !scope.length || !acceptance.length) fail("Supply concrete scope/acceptance arguments and choose an independent reviewer.");
    acquireClaim({ actor: who, task: id, mode: "local", recordedBy: who, claimedAt: new Date().toISOString(), head: git("rev-parse", "HEAD") }, () => {
      t.scope = scope; t.acceptance = acceptance; t.owner = owner; t.reviewer = reviewer; t.status = "ready"; s.activeTask = id; save(s);
    });
    rmSync(LOCK, { recursive: true }); console.log(`Assigned ${id} to ${owner}, review by ${reviewer}.`);
  } else fail(`Unknown command ${command}. See docs/team/PROTOCOL.md.`);
} catch (error) { console.error(`project-sync: ${error.message}`); process.exitCode = 1; }
